Return data correctly for webp requests
TakatoshiMaeda/kinu pull request #72
Opened 2021-06-29 09:46 UTC by fukajun

2021-06-30 05:28 UTC, 0tany commented on handler_sandbox.go
> -	}
これ消して大丈夫なやつですか？

2021-06-30 05:29 UTC, takatoshi-maeda approved these changes

2021-06-30 05:33 UTC, fukajun commented on handler_sandbox.go
> -	}
関数定義が変更されてerr自体を返さなくなったみたいです
https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/generator.go#L68

2021-06-30 05:38 UTC, fukajun commented on handler_sandbox.go
> -	}
いやなんか勘違いしてるかもしれない。もう一度確認してみますね。

2021-06-30 05:44 UTC, 0tany commented on handler_sandbox.go
> -	}
なるほど

2021-06-30 05:44 UTC, 0tany approved these changes

2021-06-30 05:49 UTC, mdoi commented on Dockerfile
> +    cd ImageMagick-${IMAGE_MAGICK_VERSION} && ./configure &&  make  && make install && ldconfig && \
旧版と新版で結構 imagemagick の Delegates が違いそう(./configure に与えるオプションが違ってそう)ですが、kinu から呼ぶ時に特に関係ない落としても問題ない機能が落ちてるんですかね？
あたりが気になりました。

```
// 旧kinuコンテナ
root@7be10b94d8b8:/# convert --version
Version: ImageMagick 6.9.6-2 Q16 x86_64 2016-10-13 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

```
// 新kinuコンテナ
root@07965b2cb0b3:/kinu-build# convert --version
Version: ImageMagick 6.9.12-17 Q16 x86_64 2021-06-25 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC OpenMP(4.5)
Delegates (built-in): jng jpeg png webp zlib
```

2021-06-30 06:56 UTC, fukajun commented on handler_sandbox.go
> -	}
https://github.com/satori/go.uuid/blob/v1.2.0/generator.go#L64 v1.2.0を利用しているのでコチラのURLが正しいものです。
go moduleによる管理に切り替えたときにgo.uuidは `master` から `v1.2.0` を利用するように変わったみたいです。そのときに、errorを返さない実装に変わったため修正したという流れです。  @0tany

2021-06-30 07:30 UTC, fukajun commented on Dockerfile
> +    cd ImageMagick-${IMAGE_MAGICK_VERSION} && ./configure &&  make  && make install && ldconfig && \
gif, png, jpg, webpのみ必要なのでインストールするパッケージを絞りました。
旧版ではaptで `libmagickwand-dev` をインストールしていたので関連パッケージも一緒にインストールされて
色々なパッケージをサポートしてたみたいです。
今回特定バージョンのImageMagickを使うためにソースから作ることにしたので、libmagickwand-devは
不要になりましたが、削除すると関連するlibjpg, libpng なども入らなくなるため
必要なフォーマットライブラリのみインストールする方針にしました。

途中、関連するフォーマットライブラリがほしかったのでlibmagickwand-devをapt installした後にapt removeするとかしてたけどイマイチなのと、docker imageサイズを小さくしたかったのでやめました。

2021-06-30 07:31 UTC, mdoi approved these changes

2021-10-12 09:45 UTC, fukajun commented
gz形式のやつがなくなっていたので、マイナーバージョンだけ上げたものを使うようにした。

2021-12-08 07:29 UTC, fukajun commented
前回のレビューから https://github.com/tokubai/kinu/pull/72/commits/7f0513755ff3384d19a67909c05d87ea0a83f4e2 以降のコミットで変更しているので、再レビューお願いします。

2021-12-08 07:35 UTC, 0tany commented on go.mod
> +replace github.com/tokubai/kinu => ./
[確認] replace残したままにするのって意図通りですか？

2021-12-09 01:54 UTC, 0tany commented on go.mod
> +replace github.com/tokubai/kinu => ./
https://go.dev/doc/modules/managing-dependencies#unpublished
ユースケース的に問題なさそうなのでこのままで 🙏

2021-12-09 02:42 UTC, fukajun commented on go.mod
> +module github.com/tokubai/kinu
自分自身のmodule名を正しくして、replaceを削除しました。

2021-12-09 02:44 UTC, fukajun commented on go.mod
> +replace github.com/tokubai/kinu => ./
自分自身がgithub.com/tokubai/kinuであるということを書けば、replaceは必要なかった
https://github.com/tokubai/kinu/pull/72/commits/7ab096ea8f8a3495eeac661b4480c2bbf5aaac6a

2021-12-09 05:09 UTC, 0tany approved these changes

2021-12-09 16:19 UTC, takatoshi-maeda requested changes

2021-12-09 16:19 UTC, takatoshi-maeda commented on Dockerfile
> +ENV KINU_VERSION 1.0.0.alpha14
僕が残した残骸ですが、 1.0.0 にしても良さそう...

2021-12-09 16:19 UTC, takatoshi-maeda commented on handler_sandbox.go
> -	}
errorは返却されないものの、Nil(実態はemptyなbyte array)が返却される [★](https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/generator.go#L169 ) [★](https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/uuid.go#L72) [★](https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/uuid.go#L37) ので、Nilであった場合のケアを明示的に行い、何らかの要因で処理が競合する(Nil値でUUIDが競合する)リスクをケアしたほうが良さそうです

2021-12-14 07:10 UTC, fukajun commented on handler_sandbox.go
> -	}
現在使用しているバージョン、v1.2.0[★](https://github.com/satori/go.uuid/blob/v1.2.0/generator.go#L151-L158)では、err返却はなく、nilにもならない[★](https://pkg.go.dev/crypto/rand#Read)の代わりに `panic` が内部的に起きるみたいです。
これは、次のリリースあたりで挙動が変更されるみたい([★](https://github.com/satori/go.uuid/issues/18))で、`panic`を使わない実装になるみたいです。
指摘のリスク自体はないみたいですが、別バージョンを使ったほうが良いのでしょうか？ @takatoshi-maeda

2021-12-14 07:31 UTC, fukajun commented
https://github.com/tokubai/kinu/pull/72#discussion_r768370458 について返信しました

2021-12-14 13:36 UTC, takatoshi-maeda commented on handler_sandbox.go
> -	}
差し替えのコストがさほどないなら、差し替えてしまったほうが良いと思います。確率はとても低く無視もできる範囲だとは思いますが、panic起こすとプロセス落ちちゃうので

2021-12-24 16:56 UTC, fukajun commented on Dockerfile
> +ENV KINU_VERSION 1.0.0.alpha14
https://github.com/tokubai/kinu/pull/72/commits/fdefaa8df952ba24cf95a4a962225192dd943747

2021-12-24 16:56 UTC, fukajun commented on handler_sandbox.go
> -	}
https://github.com/tokubai/kinu/pull/72/commits/79fd0f851326c7d8748262ddd80cc1773032c79d

2021-12-30 05:08 UTC, takatoshi-maeda approved these changes

2022-01-21 05:36 UTC, merged